EXTRA_SRC = ../public ./wred ./virtualIF ./qm ./ctrl_info ./bm ../packet 
EXTRA_INC = ../stream
TARGET_ARCH = linux64
MODULE = ftm
#SRCS = pkt.cpp tx.cpp rx.cpp access_file.cpp timer.cpp host.cpp main.cpp
#OBJS = $(SRCS:.cpp=.o)

include ./Makefile.defs

