EXTRA_SRC = ../../../public/ ../../include/qcu/ ../../include/public ../../src/sch
EXTRA_INC = 
TARGET_ARCH = linux64
MODULE = sch
#SRCS = pkt.cpp tx.cpp rx.cpp access_file.cpp timer.cpp host.cpp main.cpp
#OBJS = $(SRCS:.cpp=.o)

include ./Makefile.defs
# g++5 testbench.cpp -I../../../third-party/systemc/lib/include -I../../../third-party/sockets/include -I../../../public/ -I../../../third-party/ini  -I../../src/qcu/ -I../../include/public  -L../../../systemc/lib/lib-linux64 -lsystemc
