TARGET_ARCH = linux64
MODULE = stream
#PUBLIC = ../fap/public
PACKET = ../packet
PUBLIC = ../public
FTM_PUBLIC = ../ftm/include/public/
XML = ../third-party/tinyxml/
INI = ../third-party/ini/

#SRCS = pkt.cpp tx.cpp rx.cpp timer.cpp host.cpp main.cpp
#SRCS = $(wildcard ./*.cpp)
#OBJS = $(SRCS:.cpp=.o)

include ./Makefile.defs
